In [1]:
import pandas as pd
import numpy as np
import datetime
import time
import pickle
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline
from collections import Counter
from random import choices, sample
from gensim.models import Word2Vec
import gc
pd.set_option('display.float_format',lambda x : '%.2f' % x)
from math import log10

In [2]:
from os import listdir
from os.path import isfile, isdir, join

# 指定要列出所有檔案的目錄
mypath = './dien_dart'
# 取得所有檔案與子目錄名稱
files = listdir(mypath)
csv_list = []
# 以迴圈處理
for f in files:
  # 產生檔案的絕對路徑
  fullpath = join(mypath, f)
  # 判斷 fullpath 是檔案還是目錄
  if isfile(fullpath):
#     print("檔案：", f)
    if f[-4:]=='.csv':
        csv_list.append(f)
csv_list.sort()

In [3]:
csv_list

['change_dien_rank_20190315.csv',
 'change_dien_rank_20190316.csv',
 'change_dien_rank_20190317.csv',
 'change_dien_rank_20190318.csv',
 'change_dien_rank_20190319.csv',
 'change_dien_rank_20190320.csv',
 'change_dien_rank_20190321.csv',
 'change_dien_rank_20190322.csv',
 'change_dien_rank_20190323.csv',
 'change_dien_rank_20190324.csv',
 'change_dien_rank_20190325.csv',
 'change_dien_rank_20190326.csv',
 'change_dien_rank_20190327.csv',
 'change_dien_rank_20190328.csv',
 'change_dien_rank_20190329.csv',
 'change_dien_rank_20190330.csv',
 'change_dien_rank_20190331.csv',
 'change_dien_rank_20190401.csv',
 'change_dien_rank_20190402.csv',
 'change_dien_rank_20190403.csv',
 'change_dien_rank_20190404.csv',
 'change_dien_rank_20190405.csv',
 'change_dien_rank_20190406.csv',
 'change_dien_rank_20190407.csv',
 'change_dien_rank_20190408.csv',
 'change_dien_rank_20190409.csv',
 'change_dien_rank_20190410.csv',
 'change_dien_rank_20190411.csv',
 'change_dien_rank_20190412.csv',
 'change_dien_rank_20190413.csv',
 'change_dien_rank_20190414.csv',
 'change_dien_rank_20190415.csv',
 'change_dien_rank_20190416.csv',
 'change_dien_rank_20190417.csv',
 'change_dien_rank_20190418.csv',
 'change_dien_rank_20190419.csv',
 'change_dien_rank_20190420.csv',
 'change_dien_rank_20190421.csv',
 'change_dien_rank_20190422.csv',
 'change_dien_rank_20190423.csv',
 'change_dien_rank_20190424.csv',
 'change_dien_rank_20190425.csv',
 'change_dien_rank_20190426.csv',
 'change_dien_rank_20190427.csv',
 'change_dien_rank_20190428.csv',
 'change_dien_rank_20190429.csv',
 'change_dien_rank_20190430.csv',
 'change_dien_rank_20190501.csv',
 'change_dien_rank_20190502.csv',
 'change_dien_rank_20190503.csv',
 'change_dien_rank_20190504.csv',
 'change_dien_rank_20190505.csv',
 'change_dien_rank_20190506.csv',
 'change_dien_rank_20190507.csv',
 'change_dien_rank_20190508.csv',
 'change_dien_rank_20190509.csv',
 'change_dien_rank_20190510.csv',
 'change_dien_rank_20190511.csv',
 'change_dien_rank_20190512.csv',
 'change_dien_rank_20190513.csv',
 'change_dien_rank_20190514.csv',
 'change_dien_rank_20190515.csv',
 'change_dien_rank_20190516.csv',
 'change_dien_rank_20190517.csv',
 'change_dien_rank_20190518.csv',
 'change_dien_rank_20190519.csv',
 'change_dien_rank_20190520.csv',
 'change_dien_rank_20190521.csv',
 'change_dien_rank_20190522.csv',
 'change_dien_rank_20190523.csv',
 'change_dien_rank_20190524.csv',
 'change_dien_rank_20190525.csv',
 'change_dien_rank_20190526.csv',
 'change_dien_rank_20190527.csv',
 'change_dien_rank_20190528.csv',
 'change_dien_rank_20190529.csv',
 'change_dien_rank_20190530.csv',
 'change_dien_rank_20190531.csv',
 'change_dien_rank_20190601.csv',
 'change_dien_rank_20190602.csv',
 'change_dien_rank_20190603.csv',
 'change_dien_rank_20190604.csv',
 'change_dien_rank_20190605.csv',
 'change_dien_rank_20190606.csv',
 'change_dien_rank_20190607.csv',
 'change_dien_rank_20190608.csv',
 'change_dien_rank_20190609.csv',
 'change_dien_rank_20190610.csv',
 'change_dien_rank_20190611.csv',
 'change_dien_rank_20190612.csv',
 'change_dien_rank_20190613.csv',
 'change_dien_rank_20190614.csv',
 'change_dien_rank_20190615.csv',
 'change_dien_rank_20190616.csv',
 'change_dien_rank_20190617.csv',
 'change_dien_rank_20190618.csv',
 'change_dien_rank_20190619.csv',
 'change_dien_rank_20190620.csv',
 'change_dien_rank_20190621.csv',
 'change_dien_rank_20190622.csv',
 'change_dien_rank_20190623.csv',
 'change_dien_rank_20190624.csv',
 'change_dien_rank_20190625.csv',
 'change_dien_rank_20190626.csv',
 'change_dien_rank_20190627.csv',
 'change_dien_rank_20190628.csv',
 'change_dien_rank_20190629.csv',
 'change_dien_rank_20190630.csv']

In [4]:
lt_df_dien_dart = []

In [5]:
for file_name in tqdm(csv_list):
    lt_df_dien_dart.append(pd.read_csv('./dien_dart/' + file_name))

100%|██████████| 108/108 [00:01<00:00, 58.39it/s]

In [18]:
full_table = pd.concat(lt_df_dien_dart[:], ignore_index=True).drop('Unnamed: 0', axis=1)

In [19]:
full_table

,uid,hist_iid,last_iid,target_iid,dien_rank
0,b548e094-9db8-4230-b1b1-30f17c4fee08,e351afd4b86611e9a189acde48001122/e32d0e4ab8661...,e33fb998b86611e9bc21acde48001122,f595a7e2b86611e9ac69acde48001122,18
1,4e9e059d-0cc2-4a7b-b8f9-8fd629107dce,e3644d2eb86611e9beeeacde48001122/6c5d1e9eb8671...,e360a01eb86611e99d71acde48001122,e3644d2eb86611e9beeeacde48001122,46
2,a6aa420d-823b-42d6-ad2c-8eda5dd0dfc6,e357656eb86611e9aa0cacde48001122/e33873d4b8661...,e33873d4b86611e9a484acde48001122,e357656eb86611e9aa0cacde48001122,88
3,de780edc-c0af-4f9b-84f3-599c00a9e4d6,e36a4758b86611e986b2acde48001122,e36a4758b86611e986b2acde48001122,e32db994b86611e9bfecacde48001122,42
4,43aec705-2ed6-458f-b95f-0921aeb2df11,e35420b6b86611e9a2f4acde48001122,e35420b6b86611e9a2f4acde48001122,e34693a6b86611e999ccacde48001122,45
...,...,...,...,...,...
759021,b8a766c8-4f05-4dc2-a730-303b175be33b,0745490ab86711e99dfaacde48001122/071c7658b8671...,071c7658b86711e9a24cacde48001122,0745490ab86711e99dfaacde48001122,47
759022,43318bb1-904b-49d5-98c9-80686f96b23c,9a9a99a2b86811e9ab97acde48001122/e348fdc6b8661...,e338b418b86611e9bb17acde48001122,e374636cb86611e9a331acde48001122,59
759023,6e7f174a-b5dc-4988-ae1b-5c7da3bfeb16,5bc26eccb86711e9aff8acde48001122/5bbfc2bab8671...,179b5846b86711e98d80acde48001122,5bbfc2bab86711e9bae9acde48001122,1
759024,23fa9db7-43e5-4b80-af3a-d78144f12948,f59b93dab86611e985adacde48001122/f59b93dab8661...,f59b93dab86611e985adacde48001122,e332312cb86611e994f3acde48001122,71
759025,bce6cdcf-5b20-425d-839d-7f6f2c64981e,1760a370b86711e9969eacde48001122,1760a370b86711e9969eacde48001122,e34fc6ccb86611e9b794acde48001122,64

In [20]:
full_table.describe()

       dien_rank
count  759026.00
mean       46.77
std        30.26
min         1.00
25%        17.00
50%        48.00
75%        73.00
max        99.00